### PR TITLE
Update Performance Analyzer to support ElasticSearch version 7.3.2

### PR DESCRIPTION
**Pull request by dvjyothsna**
*Description of changes:*
* Updated the ES and OD versions in build.gradle
* Updated the gradle version
* Added release notes
* Modified WhoAmIAction to extend ActionType and CollectMetricsTests based on changes in ES

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dvjyothsna** [comment]
@ktkrg Please  review

**Comment by ktkrg** [comment]
Please update the PR with a brief description of your changes.

**Comment by dvjyothsna** [comment]
@ktkrg Updated the PR.

**Comment by dvjyothsna** [comment]
@ktkrg @ditac Resolved the conflict in release-notes. Can you please review.

**Pull request merged**
