### PR TITLE
Configure spotless plugin and enable code formatting

### PR DESCRIPTION
**Pull request by jotok**
This PR adds code formatting rules to the spotless plugin configuration and adds the `spotlessApply` target as a dependency of the `compileJava` target. This means that source files will be automatically formatted during the compilation step.

The plugin is configured to "ratchet from" the main github branch. This means that code formatting will only be applied to source files that are touched in a given PR. This is to avoid creating a huge PR by reformatting every Java file at once. In order to demonstrate the plugin in this PR I triggered formatting for two source files only.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ktkrg — DISMISSED** [review]

**Review by yu-sun-77 — COMMENTED** [review]
Can we run github workflow and make sure all the checks are passing? Otherwise LGTM.

**Review by yu-sun-77 — DISMISSED** [review]
LGTM

**Review by yu-sun-77 — APPROVED** [review]
Can we create 2 issues to track the following item before merging?
1.track failed UT
2.track code coverage check

Otherwise LGTM.

**Review by hxiao608 — APPROVED** [review]
LGTM!

**Comment by jotok** [comment]
Tracking issues for the code coverage failure and the flaky tests: #298 #299

**Pull request merged**
